#!/usr/bin/env bash

if [[ $EUID -eq 0 ]]
then
    echo "Please run as non-root user."
    exit 1
fi

DOCKER_DEVBOX_HOME=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
echo $DOCKER_DEVBOX_HOME

cd "${DOCKER_DEVBOX_HOME}"/cfssl && docker-compose down -v --remove-orphans && cd "${DOCKER_DEVBOX_HOME}"
cd "${DOCKER_DEVBOX_HOME}"/portainer && docker-compose down -v --remove-orphans && docker-compose up -d && cd "${DOCKER_DEVBOX_HOME}"
cd "${DOCKER_DEVBOX_HOME}"/traefik && docker-compose down -v --remove-orphans && docker-compose up -d && cd "${DOCKER_DEVBOX_HOME}"

rm -Rf "$HOME/.smartcd"
rm -Rf "$HOME/.smartcd_config"

echo "Run the following command in your shell to terminate uninstall:"
echo "cd ~ && rm -Rf \"${DOCKER_DEVBOX_HOME}\""