#!/usr/bin/env bash

if [[ $EUID -eq 0 ]]
then
    echo "Please run as non-root user."
    exit 1
fi

_remove_containers() {
  local CONTAINER="$1"

  if [ $(docker ps --filter "name=${CONTAINER}" | wc -l) -gt 1 ]; then
    echo "Removing container $CONTAINER" 2>&1 | tee -a "$_LOG"
    docker stop $(docker ps -a -q --filter "name=${CONTAINER}") &>> "$_LOG"
    docker rm $(docker ps -a -q --filter "name=${CONTAINER}") &>> "$_LOG"
  fi
}

DOCKER_DEVBOX_HOME=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
echo $DOCKER_DEVBOX_HOME

_remove_containers "coredns"
_remove_containers "cfssl"
_remove_containers "portainer"
_remove_containers "traefik"

rm -Rf "$HOME/.smartcd"
rm -Rf "$HOME/.smartcd_config"

echo "Run the following command in your shell to terminate uninstall:"
echo "cd ~ && rm -Rf \"${DOCKER_DEVBOX_HOME}\""