#!/usr/bin/env bash
# Upgrade script for Docker Devbox
# This script is intended to be run as a non-root user
# You can run it like this:
# curl -L https://github.com/inetum-orleans/docker-devbox/raw/master/upgrade | bash

if [[ $EUID -eq 0 ]]
then
    echo "Please run as non-root user."
    exit 1
fi

DOCKER_DEVBOX_HOME="${DOCKER_DEVBOX_HOME:-$HOME/.docker-devbox}"

ddb self-update

SERVICES=("cfssl" "portainer" "traefik")
for SERVICE in "${SERVICES[@]}"; do
    cd "${DOCKER_DEVBOX_HOME}/${SERVICE}" && git pull && ddb configure && docker compose up -d --pull always
done